'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegisterExternalLogin

    $if$ ($targetframeworkversion$ == 4.0)
    '''<summary>
    '''providerMessage 控件。
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents providerMessage As Global.System.Web.UI.WebControls.Label
    $endif$

    '''<summary>
    '''userNameForm 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents userNameForm As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''userName 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents userName As Global.System.Web.UI.WebControls.TextBox

    $if$ ($targetframeworkversion$ == 4.0)
    '''<summary>
    '''userNameMessage 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents userNameMessage As Global.System.Web.UI.WebControls.Label
    $endif$
End Class
